#! /bin/sh

sxhkd &

if xrandr --listmonitors | grep "Monitors: 3"
then
    sh ~/.screenlayout/two_external_monitors.sh
    bspc monitor eDP-1 -d 1 2 3 4
    bspc monitor HDMI-2 -d 5 6 7
    bspc monitor DP-1 -d 8 9 10
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

sh ~/.fehbg &
polybar main &

bspc config border_width         2
bspc config window_gap           5

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config focused_border_color "#fe8019"
bspc config normal_border_color  "#4c566a"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

bspc rule -a polybar manage=off
