#! /bin/sh

sxhkd &
sh ~/.fehbg &
polybar main &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config focused_border_color "#fe8019"
bspc config normal_border_color  "#4c566a"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

bspc rule -a polybar manage=off
